services:
  vsgraphs:
    image: vsgraphs
    build:
      context: .
      dockerfile: Noetic.Dockerfile
      ssh:
        - default
      args:
        USERNAME: $USERNAME
        USER_UID: 1000
        USER_GID: 1000
    container_name: vsgraphs
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      TERM: $TERM
      SHELL: $SHELL
    runtime: nvidia
    privileged: true
    restart: always
    volumes:
      # Display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - ~/.Xauthority:/root/.Xauthority:rw
      - $XAUTHORITY:$XAUTHORITY:rw
      # SSH
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      # TMUX
      - ~/.tmux:/root/.tmux:ro
      - ~/.tmux.conf:/root/.tmux.conf:ro
      # Git
      - ~/.gitconfig:/root/.gitconfig_local
      # Dev
      - /dev:/dev:rw
      # Working Directories (** MODIFY **)
      - "/home/asier/mydockers/ubuntu24/ros_ws:/home/asier/ros2_ws"
      # Data Directories (** MODIFY **)
      - "/home/asier/Documents/datasets:/home/asier/datasets"
    network_mode: "host"
    command:
      tail -f /dev/null
      # Used to set correct U/G(ID) for shared folder
  #   depends_on:
  #     - volume-init
  # # volume-init:
  #   image: busybox
  #   command: ["chown", "-R", "1000:1000", "/home/asier/ros2_ws"]
  #   volumes:
  #     # Working Directories (** MODIFY **)
  #     - "/home/asier/mydockers/ubuntu24/ros_ws:/home/asier/ros2_ws"
  #   entrypoint: ""
  #   restart: "no"